### ISSUE TITLE
engine don‘t work well on win7?

### ISSUE THREAD

**Issue by liaozc** [gongminmin/KlayGE#123]
I setup the engine on a win10 computer,and it works just as well. However,when I try to do the same thing on a win7 computer, some issues happen. First the d3dcompiler_47.dll doesn't fit, I copy the local one in windows kits 8.1 to replace it. After this, the build-in examples don't draw anything(overlay works well at the same time), instead, it keeps flickering. 
ps: there are some error message about the compiling of some shaders. " cannot have divergent gradient operations inside flow control"

**Comment by gongminmin** [comment]
The latest d3dcompiler_47.dll is from Win10 v1703. It may have some dependencies in only Win10. Try old d3dcompiler_47.dlls from those packages:

https://github.com/gongminmin/KlayGEDependencies/raw/ac9ddfae83621b79a43b0c0bd834eddf4638c19d/External/Downloads/UniversalDXSDK.7z

or

https://github.com/gongminmin/KlayGEDependencies/raw/ad787fbcbe77410ea25ebfe8b17644d8b1f38480/External/Downloads/UniversalDXSDK.7z

or 

https://github.com/gongminmin/KlayGEDependencies/raw/4e68d63d23014a75a72883d886eaf90324da6163/External/Downloads/DXSDK.7z

If any of it works, please tell me. I'll replace the file.

On the other hand, I have a report about FXAA.fxml couldn't build by Win8's d3dcompiler_47.dll. I'll fix that, too.

**Comment by liaozc** [comment]
All of them work. In fact ,two of them are the same. I only do my test on x64, hoping they also work on x86.

**Comment by gongminmin** [comment]
OK, then it must be something in v1703's d3dcompiler that doesn't work on Win7. Thanks.
