### ISSUE TITLE
About  build-in tutorials

### ISSUE THREAD

**Issue by liaozc** [gongminmin/KlayGE#125]
1.Should  the sample “RasterizationOrder ”  be supposed to run only on DX12?  Ingore this  if true, Otherwise, it seems to be  a bug that "D3D11ShaderObject" fails the "RasterizationOrder.fxml" .

2.There seems to be something wrong about the ResLoader system, the sample "VertexDisplacement" crash quite often when loading the .uiml file(NOT every time). I am pretty sure it is  a problem of thread safe.

**Comment by gongminmin** [comment]
1. It's fixed a couple days ago in https://github.com/gongminmin/KlayGE/commit/09a3a2f6b9007ac7d8be6b4b0dfe252d68299fa4.

2. I don't have a repro here. I'll try more times.

**Comment by gongminmin** [comment]
The problem of 2) is a non-reentry-able SubThreadStage. Fixed.
