### ISSUE TITLE
LNK4098: 默认库“MSVCRT”与其他库的使用冲突

### ISSUE THREAD

**Issue by jianghaosen** [gongminmin/KlayGE#135]
执行build_external.py编译python的默认是Multi-threaded DLL
编译KlayGE默认是Multi-threaded Debug DLL
两者link的时候会有LNK4098: 默认库“MSVCRT”与其他库的使用冲突

**Comment by gongminmin** [comment]
Debug模式下都会用Multi-threaded Debug DLL，而且生成的lib/dll都有_d后缀。其他模式用的Multi-threaded DLL，而且生成的lib/dll没有_d。所以如果模式一致是不会出现link冲突的。

能贴出你的cfg_build.py吗。

**Comment by jianghaosen** [comment]
cfg_build.py都是默认的auto

################################################
# !!!! DO NOT DELETE ANY FIELD OF THIS FILE !!!!
################################################

# Project type.
#   On Windows desktop, could be "vs2017", "vs2015", "make", "auto".
#   On Windows store, could be "vs2017", "vs2015", "auto".
#   On Android, could be "make", "auto".
#   On Linux, could be "make", "auto".
#   On macOS, could be "xcode", "auto".
#   On iOS, could be "xcode", "auto".
project			= "auto"

# Compiler name.
#   On Windows desktop, could be "vc141", "vc140", "clangc2", "mingw", "auto".
#   On Windows store, could be "vc141", "vc140", "auto".
#   On Android, could be "clang", "auto".
#   On Linux, could be "gcc", "auto".
#   On macOS, could be "clang", "auto".
#   On iOS, could be "clang", "auto".
compiler		= "auto"

# Target CPU architecture.
#   On Windows desktop, could be "x86", "x64".
#   On Windows store, could be "arm", "x86", "x64".
#   On Android, cound be "armeabi-v7a", "arm64-v8a", "x86", "x86_64".
#   On Linux, could be "x86", "x64".
#   On macOS, could be "x64".
#   On iOS, could be "arm", "x86".
arch			= ("x64", )

# Configuration. Could be "Debug", "Release", "MinSizeRel", "RelWithDebInfo".
config			= ("Debug", "RelWithDebInfo")

# Target platform for cross compiling.
#   On Windows desktop, could be "auto".
#   On Windows store, could be "win_store 10.0".
#   On Android, cound be "android 5.1", "android 6.0", "android 7.0", "android 7.1".
#   On Linux, could be "auto".
#   On macOS, could be "auto".
#   On iOS, could be "ios".
target			= "auto"

# A name for offline FXML compiling. Could be one of "d3d_11_0", "gles_3_0", "gles_3_1", "gles_3_2", or "auto".
shader_platform_name	= "auto"

**Comment by gongminmin** [comment]
那么检测到的编译器是什么呢？

我这边并没有复现这个问题。

**Comment by jianghaosen** [comment]
-- Build files have been written to: E:/Git/KlayGE/External/boost/Build/vs2017_vc141_win_x64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.3
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

**Comment by gongminmin** [comment]
你可以删掉External\Python\Build\vs2017_vc141_win_x64，再试一次。

**Comment by jianghaosen** [comment]
删掉可以
