### ISSUE TITLE
build failed on mac 

### ISSUE THREAD

**Issue by bruesky** [gongminmin/KlayGE#136]
The following build commands failed:
	CompileC /Users/mymac/Desktop/KlayGE_4_11_0/KlayGE/Build/xcode_clang81_darwin_x64/Engine/Core/KlayGE.build/Debug/KlayGE_Core.build/Objects-normal/x86_64/WindowDarwin.o /Users/mymac/Desktop/KlayGE_4_11_0/KlayGE/Core/Src/AppLayer/WindowDarwin.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[E] Build KlayGE failed.

**Comment by nomadfighter** [comment]
same problem, Private key 'keep_screen_on_' is not used

**Comment by bruesky** [comment]
@nomadfighter 你解决了吗？我现在只在Windows上学习了，Mac上编不过

**Comment by nomadfighter** [comment]
这个问题好解决，但是后面编译到MeshConv的时候还会报错
./KlayGE/External/assimp/include/assimp/types.h:208:19: Taking address of packed member 'r' of class or structure 'aiColor3D' may result in an unaligned pointer value
一下没想到怎么解决
不过引擎的核心模块都能编译出来了,但是运行的时候还要依赖wine？我选择了opengl啊

**Comment by bruesky** [comment]
@nomadfighter 我打开编译报一堆错，现在没在Mac弄了，回去再试试看

**Comment by gongminmin** [comment]
wine的安装可以参考 http://www.klayge.org/wiki/index.php/%E5%AE%89%E8%A3%85 。在非win平台上，会通过wine来调用d3dcompiler_47.dll编译HLSL，所以这是必须的。

assimp编译失败的情况，以前是可以的，估计现在clang升级了把这个视为错误。我打算升级到assimp的新版本，看看能不能解决这个问题。

**Comment by gongminmin** [comment]
Fixed on XCode 9.
