### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [gongminmin/KlayGE#138]
I would like to point out that identifiers like “[`_KLAYGE_CORE_AUDIO_FACTORY_HPP`](https://github.com/gongminmin/KlayGE/blob/e762741d5b31aac4efed61f4c987bf779c5d4a5f/KlayGE/Core/Include/KlayGE/AudioFactory.hpp#L31 "Update candidate")” and “[`_RENDEREFFECT_HPP`](https://github.com/gongminmin/KlayGE/blob/d8730cfedf39c92fcb20499a0d7306646100e899/KlayGE/Core/Include/KlayGE/RenderEffect.hpp#L52 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gongminmin** [comment]
New header will follow no leading or trailing underscores rule. Old header guard will be changed step-by-step. Although I'm not worry about conflict. Because they are practically impossible to conflict with any pre-defined macros.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
