### ISSUE TITLE
 Build boost failed.

### ISSUE THREAD

**Issue by bruesky** [gongminmin/KlayGE#154]
[vcvarsall.bat] Environment initialized for: 'x86_x64'
MSBUILD : error MSB1009: 项目文件不存在。
开关:ALL_BUILD.vcxproj
[E] Build boost failed.
请按任意键继续. . .

**Comment by bruesky** [comment]
Win7 vs2017 python 2.7.11 Cmake 3.10

**Comment by gongminmin** [comment]
Dup of #155.
