### ISSUE TITLE
boost build failed

### ISSUE THREAD

**Issue by bruesky** [gongminmin/KlayGE#155]
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: D:/KlayGE_4_11_0/External/boost/Build/vs201
7_vc141_win_x64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.5.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
MSBUILD : error MSB1009: 项目文件不存在。
开关:ALL_BUILD.vcxproj
[E] Build boost failed.

**Comment by gongminmin** [comment]
It has been fixed in this change https://github.com/gongminmin/KlayGE/commit/7bf435d9f1cc11a47311f15560e40174b0ce8f6e

**Comment by bruesky** [comment]
wait for 4.12 release

**Comment by gongminmin** [comment]
You can just pick that change, only 2 lines.

**Comment by bruesky** [comment]
vs2017 vc141 build 4.11.0 and 4.11.1 error below:
LINK : error LNK1218: warning treated as error; no output file generated [T:\Desktop\KlayGE_4_11_0\KlayGE\Build\vs2017_
vc141_win_x64\Engine\Plugins\Audio\OpenAL\KlayGE_AudioEngine_OpenAL.vcxproj]

**Comment by bruesky** [comment]
and develop branch have download hash dismatch errors

**Comment by bruesky** [comment]
mac dev branch build succeeded !!!
