### ISSUE TITLE
帮忙看下这个是什么原因（mac环境）

### ISSUE THREAD

**Issue by hungry0** [gongminmin/KlayGE#157]
-- Downloading https://raw.githubusercontent.com/gongminmin/KlayGEDependencies/cbda47a1678ce70b6720856736100979d469e159/KlayGE/media/Textures/2D/powered_by_klayge.dds...
CMake Error at /Users/lize/Workspace/gitProject/KlayGE/cmake/Common.cmake:125 (FILE):
  FILE DOWNLOAD HASH mismatch

    for file: [/Users/lize/Workspace/gitProject/KlayGE/KlayGE/../KlayGE/media/Textures/2D/powered_by_klayge.dds]
      expected hash: [21346648b14a0366de7abd628393e6de0253317d]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [7;"Couldn't connect to server"]

**Comment by gongminmin** [comment]
"Couldn't connect to server"已经很明显告诉你原因了。你网络太差。

**Comment by hungry0** [comment]
大佬这个需要梯子吗，感谢回答

**Comment by gongminmin** [comment]
都已经开始下这个文件了，就说明前面几个文件已经下好。所以那时候服务器能连上。也就是说，是你的网络断断续续造成的。

**Comment by hungry0** [comment]
好，感谢

**Comment by hungry0** [comment]
/Users/lize/Workspace/gitProject/KlayGE/KlayGE/Plugins/Src/Render/NullRender/NullShaderObject.cpp:139:20: error: 
      cannot initialize a parameter of type 'std::ios_base::seekdir' with an
      rvalue of type 'int'
                        res->seekg(len, 1);
                                        ^
In file included from /Users/lize/Workspace/gitProject/KlayGE/KlayGE/Plugins/Src/Render/NullRender/NullShaderObject.cpp:39:
/Users/lize/Workspace/gitProject/KlayGE/KlayGE/../KFL/include/KFL/ResIdentifier.hpp:86:53: note: 
      passing argument to parameter 'way' here
大佬帮忙看下。

**Comment by gongminmin** [comment]
把那行的1改成std::ios_base::cur就行了。修正会出现在4.12。
