### ISSUE TITLE
External: get compile error when build python 3.5.1 with ndk (develop branch)

### ISSUE THREAD

**Issue by linuxaged** [gongminmin/KlayGE#16]
Building Python...

	D:\workspace\KlayGE\External\Python\Build\gcc49_android_armeabi-v7a-Debug>cmake -G "MinGW Makefiles"  -D BUILTIN_COLLECTIONS:BOOL="ON" -D BUIL
	TIN_FUNCTOOLS:BOOL="ON" -D BUILTIN_IO:BOOL="ON"                 -D BUILTIN_ITERTOOLS:BOOL="ON" -D BUILTIN_MATH:BOOL="ON" -D BUILTIN_MSI:BOOL="
	OFF"            -D BUILTIN_OPERATOR:BOOL="ON" -D BUILTIN_UNICODEDATA:BOOL="ON" -D BUILTIN_MSVCRT:BOOL="OFF"             -D BUILTIN_WINREG:BOOL
	="ON" -D BUILTIN_SUBPROCESS:BOOL="OFF"          -D BUILTIN_SELECT:BOOL="OFF" -D BUILTIN_SOCKET:BOOL="OFF" -D BUILTIN_MMAP:BOOL="OFF"
	-D ENABLE_AUDIOOP:BOOL="OFF" -D ENABLE_CODECS_CN:BOOL="OFF" -D ENABLE_CODECS_HK:BOOL="OFF" -D ENABLE_CODECS_ISO2022:BOOL="OFF"          -D ENA
	BLE_CODECS_JP:BOOL="OFF" -D ENABLE_CODECS_KR:BOOL="OFF" -D ENABLE_CODECS_TW:BOOL="OFF"          -D ENABLE_LOCALE:BOOL="OFF" -D ENABLE_MULTIBYT
	ECODEC:BOOL="OFF" -D ENABLE_MULTIPROCESSING:BOOL="OFF"          -D ENABLE_OSSAUDIODEV:BOOL="OFF" -D ENABLE_SCPROXY:BOOL="OFF"           -D USE
	_SYSTEM_Curses:BOOL="OFF" -D USE_SYSTEM_EXPAT:BOOL="OFF" -D USE_SYSTEM_DB:BOOL="OFF" -D USE_SYSTEM_GDBM:BOOL="OFF"              -D USE_SYSTEM_
	OpenSSL:BOOL="OFF" -D USE_SYSTEM_READLINE:BOOL="OFF" -D USE_SYSTEM_SQLITE3:BOOL="OFF" -D USE_SYSTEM_TCL:BOOL="OFF"              -D USE_SYSTEM_
	ZLIB:BOOL="OFF" -DKLAYGE_ARCH_NAME:STRING="armeabi-v7a" -DCMAKE_TOOLCHAIN_FILE="D:\workspace\KlayGE/cmake/android.toolchain.cmake" -DANDROID_N
	ATIVE_API_LEVEL=10 -DCMAKE_MAKE_PROGRAM="D:\workspace\android-ndk-r10e\prebuilt\windows-x86_64\bin\make.exe" -DCMAKE_BUILD_TYPE:STRING="Debug"
	 -DANDROID_ABI=armeabi-v7a -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9 ../cmake
	-- Adjusting Android API level 'android-10' to 'android-9'
	CMake Warning (dev) at D:/workspace/KlayGE/cmake/android.toolchain.cmake:1655 (if):
	  Policy CMP0054 is not set: Only interpret if() arguments as variables or
	  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
	  details.  Use the cmake_policy command to set the policy and suppress this
	  warning.

	  Quoted variables like "LIBRARY_OUTPUT_PATH_ROOT" will no longer be
	  dereferenced when the policy is set to NEW.  Since the policy is not set
	  the OLD behavior will be used.
	Call Stack (most recent call first):
	  D:/workspace/KlayGE/External/Python/Build/gcc49_android_armeabi-v7a-Debug/CMakeFiles/3.4.1/CMakeSystem.cmake:6 (include)
	  CMakeLists.txt:8 (project)
	This warning is for project developers.  Use -Wno-dev to suppress it.

	-- The system name is Android
	-- The system version is 1
	-- Looking for CMake command configure_package_config_file
	-- Looking for CMake command configure_package_config_file - found
	-- Looking for CMake command write_basic_package_version_file
	-- Looking for CMake command write_basic_package_version_file - found
	-- ptmx: HAVE_DEV_PTMX-NOTFOUND ptc: HAVE_DEV_PTC-NOTFOUND
	-- Checking for XOPEN_SOURCE
	-- Checking for XOPEN_SOURCE - yes
	-- Checking for Large File Support
	-- Checking for Large File Support - yes
	-- Checking whether C doubles are little-endian IEEE 754 binary64
	-- Checking whether C doubles are little-endian IEEE 754 binary64 - no
	-- Checking whether C doubles are big-endian IEEE 754 binary64
	-- Checking whether C doubles are big-endian IEEE 754 binary64 - no
	-- Checking doubles are ARM mixed-endian IEEE 754 binary64
	-- Checking doubles are ARM mixed-endian IEEE 754 binary64 - no
	CMake Warning (dev) at cmake/PlatformTest.cmake:8 (IF):
	  Policy CMP0054 is not set: Only interpret if() arguments as variables or
	  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
	  details.  Use the cmake_policy command to set the policy and suppress this
	  warning.

	  Quoted variables like "HAVE_GCC_ASM_FOR_X87_COMPILED" will no longer be
	  dereferenced when the policy is set to NEW.  Since the policy is not set
	  the OLD behavior will be used.
	Call Stack (most recent call first):
	  cmake/ConfigureChecks.cmake:685 (python_platform_test)
	  CMakeLists.txt:87 (include)
	This warning is for project developers.  Use -Wno-dev to suppress it.

	-- Checking for x87-style double rounding
	-- Checking for x87-style double rounding - no
	-- Checking whether tanh preserves the sign of zero
	-- Checking whether tanh preserves the sign of zero - no
	-- Using unsigned short for unicode
	-- Checking whether POSIX semaphores are enabled
	-- Checking whether POSIX semaphores are enabled - no
	-- Checking for broken sem_getvalue
	-- Checking for broken sem_getvalue - no
	-- Checking for working tzset()
	-- Checking for working tzset() - no
	-- Checking for %lld and %llu printf() format support
	-- Checking for %lld and %llu printf() format support - no
	-- Checking for %zd printf() format support()
	-- Checking for %zd printf() format support() - no
	--
	-- The following extensions will NOT be built:
	--
	--     cmath (not set: HAVE_LIBM)
	--     _codecs_cn (not set: ENABLE_CODECS_CN)
	--     _codecs_hk (not set: ENABLE_CODECS_HK)
	--     _codecs_iso2022 (not set: ENABLE_CODECS_ISO2022)
	--     _codecs_jp (not set: ENABLE_CODECS_JP)
	--     _codecs_kr (not set: ENABLE_CODECS_KR)
	--     _codecs_tw (not set: ENABLE_CODECS_TW)
	--     crypt (not set: HAVE_LIBCRYPT)
	--     datetime (not set: HAVE_LIBM)
	--     _locale (not set: ENABLE_LOCALE)
	--     _multibytecodec (not set: ENABLE_MULTIBYTECODEC)
	--     time (not set: HAVE_LIBM)
	--     fcntl (not set: UNIX)
	--     grp (not set: UNIX)
	--     nis (not set: UNIX HAVE_LIBNSL)
	--     posix (not set: UNIX)
	--     pwd (not set: UNIX)
	--     resource (not set: UNIX)
	--     spwd (not set: UNIX HAVE_GETSPNAM HAVE_GETSPENT)
	--     syslog (not set: UNIX)
	--     termios (not set: UNIX)
	--     _scproxy (not set: APPLE HAVE_LIBSYSTEMCONFIGURATION ENABLE_SCPROXY)
	--     ossaudiodev (not set: LINUX ENABLE_OSSAUDIODEV)
	--     _msi (not set: WIN32)
	--     msvcrt (not set: MSVC)
	--     nt (not set: WIN32)
	--     _subprocess (not set: WIN32)
	--     winreg (not set: WIN32)
	--     _bsddb (not set: DB_INCLUDE_PATH DB_LIBRARIES)
	--     bz2 (not set: BZIP2_LIBRARIES)
	--     _curses_panel (not set: CURSES_LIBRARIES)
	--     _curses (not set: CURSES_LIBRARIES)
	--     dbm (not set: GDBM_INCLUDE_PATH GDBM_LIBRARY GDBM_COMPAT_LIBRARY)
	--     gdbm (not set: GDBM_INCLUDE_PATH GDBM_LIBRARY GDBM_COMPAT_LIBRARY)
	--     _hashlib (not set: OPENSSL_INCLUDE_DIR OPENSSL_LIBRARIES)
	--     readline (not set: READLINE_INCLUDE_PATH READLINE_LIBRARY CURSES_LIBRARIES)
	--     _sqlite3 (not set: SQLITE3_INCLUDE_PATH SQLITE3_LIBRARY)
	--     _ssl (not set: OPENSSL_INCLUDE_DIR OPENSSL_LIBRARIES)
	--     _tkinter (not set: TCL_LIBRARY TK_LIBRARY TCL_INCLUDE_PATH TK_INCLUDE_PATH)
	--     zlib (not set: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
	--
	-- Configuring done
	-- Generating done
	-- Build files have been written to: D:/workspace/KlayGE/External/Python/Build/gcc49_android_armeabi-v7a-Debug
	[  0%] Building C object CMakeBuild/libpython/CMakeFiles/libpython-static.dir/D_/workspace/KlayGE/External/Python/Modules/faulthandler.c.o
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:58:1: warning: missing initializer for field 'interp' of 'struct <anonymous>' [-Wmissing-fiel
	d-initializers]
	 } fatal_error = {0, NULL, -1, 0};
	 ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:57:25: note: 'interp' declared here
	     PyInterpreterState *interp;
	                         ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:111:5: warning: missing initializer for field 'previous' of 'fault_handler_t' [-Wmissing-fiel
	d-initializers]
	     {SIGBUS, 0, "Bus error", },
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:48:22: note: 'previous' declared here
	     _Py_sighandler_t previous;
	                      ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:114:5: warning: missing initializer for field 'previous' of 'fault_handler_t' [-Wmissing-fiel
	d-initializers]
	     {SIGILL, 0, "Illegal instruction", },
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:48:22: note: 'previous' declared here
	     _Py_sighandler_t previous;
	                      ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:116:5: warning: missing initializer for field 'previous' of 'fault_handler_t' [-Wmissing-fiel
	d-initializers]
	     {SIGFPE, 0, "Floating point exception", },
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:48:22: note: 'previous' declared here
	     _Py_sighandler_t previous;
	                      ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:117:5: warning: missing initializer for field 'previous' of 'fault_handler_t' [-Wmissing-fiel
	d-initializers]
	     {SIGABRT, 0, "Aborted", },
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:48:22: note: 'previous' declared here
	     _Py_sighandler_t previous;
	                      ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:120:5: warning: missing initializer for field 'previous' of 'fault_handler_t' [-Wmissing-fiel
	d-initializers]
	     {SIGSEGV, 0, "Segmentation fault", }
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:48:22: note: 'previous' declared here
	     _Py_sighandler_t previous;
	                      ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_dump_traceback_py':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:251:42: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_dump_traceback_py(PyObject *self,
	                                          ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_enable':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:357:31: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_enable(PyObject *self, PyObject *args, PyObject *kwargs)
	                               ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_disable_py':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:449:35: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_disable_py(PyObject *self)
	                                   ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_is_enabled':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:461:35: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_is_enabled(PyObject *self)
	                                   ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_thread':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:469:27: warning: unused parameter 'unused' [-Wunused-parameter]
	 faulthandler_thread(void *unused)
	                           ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_dump_traceback_later':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:557:45: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_dump_traceback_later(PyObject *self,
	                                             ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_cancel_dump_traceback_later_py':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:630:55: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_cancel_dump_traceback_later_py(PyObject *self)
	                                                       ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_register_py':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:733:36: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_register_py(PyObject *self,
	                                    ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_unregister_py':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:810:38: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_unregister_py(PyObject *self, PyObject *args)
	                                      ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_suppress_crash_report':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:836:5: error: unknown type name 'UINT'
	     UINT mode;
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:839:5: warning: implicit declaration of function 'SetErrorMode' [-Wimplicit-function-declarat
	ion]
	     mode = SetErrorMode(SEM_NOGPFAULTERRORBOX);
	     ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:839:25: error: 'SEM_NOGPFAULTERRORBOX' undeclared (first use in this function)
	     mode = SetErrorMode(SEM_NOGPFAULTERRORBOX);
	                         ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:839:25: note: each undeclared identifier is reported only once for each function it appears i
	n
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_read_null':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:861:34: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_read_null(PyObject *self, PyObject *args)
	                                  ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:861:50: warning: unused parameter 'args' [-Wunused-parameter]
	 faulthandler_read_null(PyObject *self, PyObject *args)
	                                                  ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_sigsegv':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:897:32: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_sigsegv(PyObject *self, PyObject *args)
	                                ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_sigfpe':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:914:31: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_sigfpe(PyObject *self, PyObject *args)
	                               ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:914:47: warning: unused parameter 'args' [-Wunused-parameter]
	 faulthandler_sigfpe(PyObject *self, PyObject *args)
	                                               ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_sigabrt':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:930:32: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_sigabrt(PyObject *self, PyObject *args)
	                                ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:930:48: warning: unused parameter 'args' [-Wunused-parameter]
	 faulthandler_sigabrt(PyObject *self, PyObject *args)
	                                                ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_fatal_error_py':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:938:39: warning: unused parameter 'self' [-Wunused-parameter]
	 faulthandler_fatal_error_py(PyObject *self, PyObject *args)
	                                       ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: In function 'faulthandler_traverse':
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:996:33: warning: unused parameter 'module' [-Wunused-parameter]
	 faulthandler_traverse(PyObject *module, visitproc visit, void *arg)
	                                 ^
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c: At top level:
	D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:1073:5: warning: missing initializer for field 'ml_flags' of 'PyMethodDef' [-Wmissing-field-i
	nitializers]
	     {NULL, NULL}  /* sentinel */
	     ^
	In file included from D:\workspace\KlayGE\External\Python\Build\cmake\..\..\Include/Python.h:91:0,
	                 from D:\workspace\KlayGE\External\Python\Modules\faulthandler.c:1:
	D:\workspace\KlayGE\External\Python\Build\cmake\..\..\Include/methodobject.h:43:17: note: 'ml_flags' declared here
	     int         ml_flags;   /* Combination of METH_xxx flags, which mostly
	                 ^
	make[2]: *** [CMakeBuild/libpython/CMakeFiles/libpython-static.dir/D_/workspace/KlayGE/External/Python/Modules/faulthandler.c.o] Error 1
	make[1]: *** [CMakeBuild/libpython/CMakeFiles/libpython-static.dir/all] Error 2
	make: *** [all] Error 2
	[E] Build Python failed.

**Comment by gongminmin** [comment]
Fixed.
