### ISSUE TITLE
Static-only build for OSX

### ISSUE THREAD

**Issue by ppiecuch** [gongminmin/KlayGE#162]
Hello, I have question: is it possible to build fully static build for OSX (probably just like the build for iOS)? I tried with KLAYGE_PREFERRED_LIB_TYPE=STATIC but this did not help.

Regards
Pawel

**Comment by gongminmin** [comment]
In theory it's possible. You need to,
1. Change the PREFERRED_LIB_TYPE in CMakeLists,
2. Change KlayGE\Core\Src\Base\Context.cpp to hard code the factory methods in such as MakeRenderFactory, MakeInputFactory, etc,
3. Non-trivial debug and test works.

In general, KlayGE's linking type is not designed to be reconfigure-able. On Android and iOS, I have to use static lib. And it just works.
