### ISSUE TITLE
build failed on win

### ISSUE THREAD

**Issue by nomadfighter** [gongminmin/KlayGE#163]
rev : 8b9188613

-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.13")
CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/yuyzc/Documents/code/KlayGE/cmake/ConfigBoost.cmake:23 (FIND_PACKAGE)
  CMakeLists.txt:33 (INCLUDE)

-- Could NOT find Boost
-- Configuring done
-- Generating done

but build success on osx!

我阅读cmake代码没有看出问题在哪里，求指教

**Comment by gongminmin** [comment]
No, it's not an error. And the build doesn't stop because of this.

The reason behind is CMake 3.10 doesn't support boost 1.66.
