### ISSUE TITLE
KlayGE Core build failed (develop branch, ndk gcc 4.9)

### ISSUE THREAD

**Issue by linuxaged** [gongminmin/KlayGE#17]
compiler		= "gcc"
toolset		= "4.9"
arch		= ("armeabi-v7a", )
config		= ("Debug", )
target		= "android"

	Scanning dependencies of target KlayGE_Core
	[  1%] Building CXX object Engine/Core/CMakeFiles/KlayGE_Core.dir/D_/workspace/KlayGE/KlayGE/Core/Src/Kernel/Context.cpp.o
	[  1%] Building CXX object Engine/Core/CMakeFiles/KlayGE_Core.dir/D_/workspace/KlayGE/KlayGE/Core/Src/Kernel/HWDetect.cpp.o
	[  2%] Building CXX object Engine/Core/CMakeFiles/KlayGE_Core.dir/D_/workspace/KlayGE/KlayGE/Core/Src/Kernel/KlayGE.cpp.o
	[  2%] Building CXX object Engine/Core/CMakeFiles/KlayGE_Core.dir/D_/workspace/KlayGE/KlayGE/Core/Src/Kernel/PerfProfiler.cpp.o
	[  3%] Building CXX object Engine/Core/CMakeFiles/KlayGE_Core.dir/D_/workspace/KlayGE/KlayGE/Core/Src/Kernel/ResLoader.cpp.o
	In file included from D:\workspace\KlayGE\KlayGE\Core\Include/KlayGE/ResLoader.hpp:55:0,
	                 from D:\workspace\KlayGE\KlayGE\Core\Src\Kernel\ResLoader.cpp:86:
	D:\workspace\KlayGE\KlayGE\..\KFL\include/KFL/Thread.hpp: In instantiation of 'KlayGE::joiner_impl_base<result_type>::const_result_type_ref KlayGE::join
	er_impl_base<result_type>::join() [with result_type = void; KlayGE::joiner_impl_base<result_type>::const_result_type_ref = void]':
	D:\workspace\KlayGE\KlayGE\..\KFL\include/KFL/Thread.hpp:229:25:   required from 'KlayGE::joiner<ResultType>::const_result_type_ref KlayGE::joiner<Resul
	tType>::operator()() [with ResultType = void; KlayGE::joiner<ResultType>::const_result_type_ref = void]'
	D:\workspace\KlayGE\KlayGE\Core\Src\Kernel\ResLoader.cpp:232:22:   required from here
	D:\workspace\KlayGE\KlayGE\..\KFL\include/KFL/Thread.hpp:161:47: error: 'class std::experimental::optional<KlayGE::void_t>' has no member named 'get'
	    return const_result_type_ref(result_->get());
	                                               ^
	D:\workspace\KlayGE\KlayGE\..\KFL\include/KFL/Thread.hpp:161:47: error: return-statement with a value, in function returning 'void' [-fpermissive]
	make[2]: *** [Engine/Core/CMakeFiles/KlayGE_Core.dir/D_/workspace/KlayGE/KlayGE/Core/Src/Kernel/ResLoader.cpp.o] Error 1
	make[1]: *** [Engine/Core/CMakeFiles/KlayGE_Core.dir/all] Error 2
	make: *** [all] Error 2
	[E] Build KlayGE failed.

**Comment by gongminmin** [comment]
Didn't reproduced here, with NDK r10e, target = "android 4.2".

**Comment by linuxaged** [comment]
Maybe you are using gcc 4.8, try `compiler = gcc` && `toolset = 4.9`

**Comment by gongminmin** [comment]
Yes, you are correct. It fails in 4.9. Starting from 4.9, libstdc++ provides std::experimental::optional, but it doesn't have get(). I'll try gcc 5.0+ and decide how to fix it. Thanks.

**Comment by gongminmin** [comment]
Fixed. The boost's optional and std::experimental have different interfaces. Now converged to std::experimantal's.
