### ISSUE TITLE
Mac developer branch External Python build error(OS X EI Capton, Xcode 7.2.1, clang-700.1.81)

### ISSUE THREAD

**Issue by speakfool** [gongminmin/KlayGE#18]
Seems some macros are not defined?

/Users/zhongtang/Programming/KlayGE/External/Python/Modules/timemodule.c:659:9: error: 
      use of undeclared identifier '_Py_BEGIN_SUPPRESS_IPH'
        _Py_BEGIN_SUPPRESS_IPH
        ^
/Users/zhongtang/Programming/KlayGE/External/Python/Modules/timemodule.c:661:9: error: 
      use of undeclared identifier '_Py_END_SUPPRESS_IPH'
        _Py_END_SUPPRESS_IPH

I tried fixed this errors by add "-DBUILD_CORE" in compiler flag
Then I got:
"SOABI" undefined in /Users/zhongtang/Programming/KlayGE/External/Python/Python/dynload_shlib.c:35:

```
const char *_PyImport_DynLoadFiletab[] = {
#ifdef __CYGWIN__
    ".dll",
#else  /* !__CYGWIN__ */
    "." SOABI ".so",
    ".abi" PYTHON_ABI_STRING ".so",
    ".so",
#endif  /* __CYGWIN__ */
    NULL,
};

```

**Comment by qiankanglai** [comment]
I've encountered this too. Easiest (& dirty) patch: add `#define SOABI "cpython-34m"`

Trying to figure a better way now

**Comment by speakfool** [comment]
Just don't know if this is the only problem.
These macros are provided by configure, in the original automake system.
I think maybe a better way is to use the provided configure/make on linux-based system?
Is this easy to integrate with CMake?
I'll see to this later after work.

**Comment by qiankanglai** [comment]
I've just tested yesterday. Other problems like Assimp has been fixed.

Python src doesn't provide a CMakeFiles...so every time I have to maintain it manually after updating :disappointed:

**Comment by speakfool** [comment]
After some digging I got this:
Add -DSOABI='"cpython-35m-darwin"' -DPy_BUILD_CORE in c compiler flag can work.  But where should I add these options? I tried "makefile-variables.in" but not working. And the SOABI value is platform specified.

**Comment by gongminmin** [comment]
This is something I don't understand. The first line of External\Python\Build\cmake\cmake\libpython\CMakeLists.txt is add_definitions(-DPy_BUILD_CORE). But somehow on OSX, Py_BUILD_CORE doesn't get through to compiler.

SOABI is definitely required. Can you confirm it's "cpython-35m-darwin"? If so, I can fix this problem by adding it to CMakeLists.txt.

**Comment by speakfool** [comment]
I tried just add it to CMAKE_C_FLAGS in the root CMakeLists.txt, and it's working somehow. I'm not familiar with CMake syntax, especially the quote rules. I don't have my Mac with me right now, hope it helps.

SOABI is platform specific, as I see in configure.ac: 4074
`SOABI='cpython-'`echo $VERSION | tr -d .`${ABIFLAGS}
`

**Comment by speakfool** [comment]
To be clear, I didn't finally add Py_BUILD_CORE. It would affect the test files and cause build failure.
I added the -D_Py_BEGIN_SUPPRESS_IPH and -D_Py_END_SUPPRESS_IPH instead.

The "cpython-35m-darwin" is what I got from running the ./configure and checked the Makefile.

**Comment by speakfool** [comment]
I thought you added Py_BUILD_CORE in libpython, but not in extensions.
I got first compile error in extension-time and extension-datetime.

**Comment by gongminmin** [comment]
Thanks for you help. I'll move the Py_BUILD_CORE to root CMakeLists, and add cpython-35m-darwin as SOABI. New commit will be pushed very soon.
