### ISSUE TITLE
Compile Error,I cant resolve it,ask for help

### ISSUE THREAD

**Issue by q453157180** [gongminmin/KlayGE#193]
![image](https://user-images.githubusercontent.com/26478499/49293869-4c0a4200-f4ec-11e8-949d-32fae487a301.png)

**Comment by gongminmin** [comment]
It's the same as this issue: https://github.com/dotnet/corefx/issues/3784.

> The fix for me was to add myself to the list of permissions of C:\Users\All Users\Microsoft\Crypto\RSA\MachineKeys folder with Full Control. A side note: I'm a participant of Administrators group and it was there with Full Control but it wasn't enough.
