### ISSUE TITLE
OGG creating errors during build

### ISSUE THREAD

**Issue by TheDunkShot** [gongminmin/KlayGE#203]
### **Python Error:**
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.17763.
CMake Deprecation Warning at Python/python-cmake-buildsystem/CMakeLists.txt:34 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

 SRC_DIR: C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Python
 PY_VERSION: 3.5.1
 The system name is Windows
 The system processor is AMD64
 The system version is 10.0.17763

 The following extensions will NOT be built:

     audioop (not set: ENABLE_AUDIOOP)
     _codecs_cn (not set: ENABLE_CODECS_CN)
     _codecs_hk (not set: ENABLE_CODECS_HK)
     _codecs_iso2022 (not set: ENABLE_CODECS_ISO2022)
     _codecs_jp (not set: ENABLE_CODECS_JP)
     _codecs_kr (not set: ENABLE_CODECS_KR)
     _codecs_tw (not set: ENABLE_CODECS_TW)
     cPickle (not set: IS_PY2)
     _crypt (not set: HAVE_LIBCRYPT)
     cStringIO (not set: IS_PY2)
     _ctypes_test (not set: ENABLE_CTYPES_TEST)
     future_builtins (not set: IS_PY2)
     _hotshot (not set: IS_PY2)
     _locale (not set: ENABLE_LOCALE)
     mmap (not set: ENABLE_MMAP)
     _multibytecodec (not set: ENABLE_MULTIBYTECODEC)
     operator (not set: IS_PY2)
     strop (not set: IS_PY2)
     _testcapi (not set: ENABLE_TESTCAPI)
     _pickle (not set: ENABLE_PICKLE)
     xxlimited (not set: BUILD_TESTING)
     fcntl (not set: UNIX)
     grp (not set: UNIX)
     nis (not set: UNIX HAVE_LIBNSL)
     posix (not set: UNIX)
     pwd (not set: UNIX)
     resource (not set: UNIX)
     spwd (not set: UNIX HAVE_GETSPNAM HAVE_GETSPENT)
     syslog (not set: UNIX)
     termios (not set: UNIX)
     errno (not set: UNIX)
     _posixsubprocess (not set: UNIX)
     _scproxy (not set: APPLE HAVE_LIBSYSTEMCONFIGURATION ENABLE_SCPROXY)
     linuxaudiodev (not set: LINUX IS_PY2 HAVE_SYS_SOUNDCARD_H)
     ossaudiodev (not set: LINUX HAVE_SYS_SOUNDCARD_H ENABLE_OSSAUDIODEV)
     _msi (not set: ENABLE_MSI)
     msvcrt (not set: ENABLE_MSVCRT)
     _subprocess (not set: IS_PY2 ENABLE_SUBPROCESS)
     _overlapped (not set: ENABLE_OVERLAPPED)
     _winapi (not set: ENABLE_WINAPI)
     _multiprocessing (not set: ENABLE_MULTIPROCESSING)
     select (not set: ENABLE_SELECT)
     _socket (not set: ENABLE_SOCKET)
     _ctypes (not set: BUILD_LIBPYTHON_SHARED ENABLE_CTYPES)
     _decimal (not set: ENABLE_DECIMAL)
     pyexpat (not set: ENABLE_PYEXPAT)
     _bsddb (not set: DB_INCLUDE_PATH DB_LIBRARIES)
     _bz2 (not set: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
     _curses_panel (not set: CURSES_LIBRARIES PANEL_LIBRARIES HAVE_PANEL_H OR HAVE_NCURSES_PANEL_H)
     _curses (not set: CURSES_LIBRARIES HAVE_CURSES_H)
     _dbm (not set: NDBM_TAG GDBM_LIBRARY GDBM_COMPAT_LIBRARY)
     _gdbm (not set: GDBM_INCLUDE_PATH GDBM_LIBRARY GDBM_COMPAT_LIBRARY)
     _hashlib (not set: OPENSSL_INCLUDE_DIR OPENSSL_LIBRARIES)
     readline (not set: READLINE_INCLUDE_PATH READLINE_LIBRARY CURSES_LIBRARIES HAVE_READLINE_READLINE_H)
     _sqlite3 (not set: SQLITE3_INCLUDE_PATH SQLITE3_LIBRARY ENABLE_SQLITE3)
     _ssl (not set: OPENSSL_INCLUDE_DIR OPENSSL_LIBRARIES)
     _tkinter (not set: TCL_LIBRARY TK_LIBRARY TCL_INCLUDE_PATH TK_INCLUDE_PATH)

 Cloning rapidjson...
 Checking out to revision 67fac85e96220f69076121d569abd15471abb6bf...
 Cloning libogg...
 Checking out to revision 0acd32d7cabf7e41cc29ea7c2bbffde969ff1ba0...
CMake Error at libogg/CMakeLists.txt:9 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source
  "C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Build/CMake/libogg/../../../libogg"
  which is not an existing directory.

CMake Error at libogg/CMakeLists.txt:11 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES Can not find target to add properties to: ogg

 Configuring vorbis 1.3.6
 Could NOT find OGG (missing: OGG_INCLUDE_DIRS)
 Creating directory C:/sadsa/kaede/Desktop/KlayGE_4_14_0/External/Build/vs2017_vc141_win_x64/freetype/freetype/include/freetype/config
 Creating file C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Build/vs2017_vc141_win_x64/freetype/freetype/include/freetype/config/ftconfig.h
 Creating file C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Build/vs2017_vc141_win_x64/freetype/freetype/include/freetype/config/ftoption.h
 Cloning assimp...
 Checking out to revision 8c15a35609e8582945aec966f263d0ee821d63ae...
CMake Error at assimp/CMakeLists.txt:29 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source
  "C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Build/CMake/assimp/../../../assimp"
  which is not an existing directory.

CMake Error at assimp/CMakeLists.txt:31 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES Can not find target to add properties to: assimp

CMake Error at assimp/CMakeLists.txt:53 (set_target_properties):
  set_target_properties Can not find target to add properties to: assimp

CMake Error at assimp/CMakeLists.txt:53 (set_target_properties):
  set_target_properties Can not find target to add properties to: IrrXML

CMake Error at assimp/CMakeLists.txt:53 (set_target_properties):
  set_target_properties Can not find target to add properties to: uninstall

 Cloning nanosvg...
 Checking out to revision 2b08deeb553c723d151f908d786c64136d26d576...
 Cloning cxxopts...
 Checking out to revision 3f2d70530219e09fe7e563f86126b0d3b228a60d...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OGG_INCLUDE_DIRS
   used as include directory in directory C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/libvorbis/lib
   used as include directory in directory C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/libvorbis/lib
   used as include directory in directory C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/libvorbis/lib
   used as include directory in directory C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/libvorbis/lib
   used as include directory in directory C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/libvorbis/lib

 Configuring incomplete, errors occurred!
See also "C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Build/vs2017_vc141_win_x64/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/gongminmin/KlayGE/files/3317016/CMakeOutput.log)

See also "C:/Users/sadsa/Desktop/KlayGE_4_14_0/External/Build/vs2017_vc141_win_x64/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/gongminmin/KlayGE/files/3317014/CMakeError.log)

**Comment by gongminmin** [comment]
Do you have the libogg under folder External\libogg? This symptom looks like libogg is not correctly checked out. In develop branch or 4.15, the building system can automatically retry if something's not right.

**Comment by TheDunkShot** [comment]
No libogg isn't in the External folder. I have tried Build_All.bat in a new folder and seems that it struggles extracting libogg.

**Comment by gongminmin** [comment]
Please try develop or release/4.15 branch. The libogg is literally clone from https://github.com/xiph/ogg.git . It should always work.

**Comment by gongminmin** [comment]
It happens when git is not in the PATH. Working on a fix.
