### ISSUE TITLE
DXBC2GLSL bug

### ISSUE THREAD

**Issue by xmuzzczlcai** [gongminmin/KlayGE#216]
false in const struct DXBCInputBindDesc &__cdecl GLSLGen::GetResourceDesc(enum ShaderInputType,unsigned int) const, line 7626 of C:\Users\xindong\Downloads\KlayGE-develop\DXBC2GLSL\Src\GLSLGen.cpp
——————————————————————————————————————————————————————————
when I try to convert .dxbc file compiled from this text:

vs_5_0
dcl_global_flags refactoringAllowed
dcl_constant_buffer cb0[12].xyzw, immediateIndexed
dcl_input v0.xyzw
dcl_output o0.xy
dcl_output o1.xyz
dcl_output_siv o2.xyzw, position
dcl_temps 2
dp4 r0.x, v0.xyzw, cb0[8].xyzw
dp4 r0.y, v0.xyzw, cb0[9].xyzw
dp4 r0.w, v0.xyzw, cb0[11].xyzw
div r1.xy, r0.xyxx, r0.wwww
mov o2.xyw, r0.xyxw
mad o0.xy, r1.xyxx, l(0.5, -0.5, 0, 0), l(0.5, 0.5, 0, 0)
dp4 o1.x, v0.xyzw, cb0[4].xyzw
dp4 o1.y, v0.xyzw, cb0[5].xyzw
dp4 o1.z, v0.xyzw, cb0[6].xyzw
dp4 o2.z, v0.xyzw, cb0[10].xyzw
ret

**Comment by gongminmin** [comment]
Could you share the dxbc file?

**Comment by gongminmin** [comment]
DXBC2GLSL requires resource chunk in dxbc. It can't process a stripped dxbc.
