### ISSUE TITLE
DXBC2GLSLCmd bug: false in const struct DXBCInputBindDesc &__cdecl GLSLGen::GetResourceDesc

### ISSUE THREAD

**Issue by zwcloud** [gongminmin/KlayGE#221]
error message:

> Error(s) in conversion:
> false in const struct DXBCInputBindDesc &__cdecl GLSLGen::GetResourceDesc(enum ShaderInputType,unsigned int) const, line 7625 of Z:\5_tools\KlayGE\DXBC2GLSL\Src\GLSLGen.cpp
> Please send this information and your bytecode file to webmaster at klayge.org. We'll fix this ASAP.

The dxbc file is saved from a renderdoc capture file:
![image](https://user-images.githubusercontent.com/6965758/109385289-b4dfff00-792d-11eb-8817-3f993bcfec33.png)

[dxbc.zip](https://github.com/gongminmin/KlayGE/files/6054225/dxbc.zip)

**Comment by gongminmin** [comment]
The resource chunk has been stripped out from the DXBC. It's not revertible. DXBC2GLSL is designed to work with the original DXBC from compiler, with reflection information in it.
