### ISSUE TITLE
Cmake failed  because of UniversalDXSDK

### ISSUE THREAD

**Issue by crazyeminem** [gongminmin/KlayGE#223]
it seems that the git repository of UniversalDXSDK does not exist anymore

**Comment by gongminmin** [comment]
It's a dup of #215 . The issue has been fixed in this change: https://github.com/gongminmin/KlayGE/commit/f5889d904edf2450d0d8f78e7bbbd2da89503750#diff-68c114ea9c8c66041e9452211afd1f4fbc6e15554179f7f5f96a73219d4937a0
