### ISSUE TITLE
How to build from source on MSYS2 MINGW64?

### ISSUE THREAD

**Issue by ghost** [gongminmin/KlayGE#231]

**Comment by WonderCooper** [comment]
您好，已收到您的邮件，我会尽快处理，谢谢

**Comment by gongminmin** [comment]
Do you mean build inside msys2 with mingw64? The MinGW in CI is msys2 mingw64. But why need to build inside msys2?

**Comment by ghost** [comment]
> Do you mean build inside msys2 with mingw64? The MinGW in CI is msys2 mingw64. But why need to build inside msys2?

Please tell me which command to use. I'm confused by the Python scripts. Could I invoke cmake directly? I think I shouldn't do so.

p/s: MSYS2 MINGW64 is an environment of MSYS2: https://www.msys2.org/docs/environments/

**Comment by gongminmin** [comment]
Yes, msys2 mingw64 is supported. But I don't run msys2 to call the script, just in cmd. 

First, you put the mingw64, say, C:\msys64\mingw64\bin, to your path. Then the command line of building is:
`Build.py ninja mingw x64 Release`

You can replace the ninja with make, if you don't have ninja install. Or replace the Release with Debug.

The Build.py can detect the compiler, and set the environment for CMake. It would be easier than just using CMake.

**Comment by ghost** [comment]
> Yes, msys2 mingw64 is supported. But I don't run msys2 to call the script, just in cmd.
> 
> First, you put the mingw64, say, C:\msys64\mingw64\bin, to your path. Then the command line of building is: `Build.py ninja mingw x64 Release`
> 
> You can replace the ninja with make, if you don't have ninja install. Or replace the Release with Debug.
> 
> The Build.py can detect the compiler, and set the environment for CMake. It would be easier than just using CMake.

Well, it seems the script expects Windows path separator so it failed to run on the MSYS2 MINGW64 Shell:

```
$ ./Build.py ninja mingw x64 Release
Generating CfgBuild.py ...
Build information:
        CMake path: C:\msys64\mingw64\bin/cmake.EXE
        CMake version: 326
        Host platform: win
        Target platform: win
        CPU count: 4
        Prefer static library: False
        Shader platform: auto
        Is dev platform: True
        Project type: ninja
        Compiler: mgw122
        Architectures: x64
        Configures: Release
        GLES SDK include path: auto
        Oculus LibOVR path: auto

Building KlayGE Release...

C:\msys64\home\Administrator\KlayGE\Build\ninja_mgw122_win_x64-Release>"C:\msys64\mingw64\bin/cmake.EXE" -G "Ninja"  -DKLAYGE_SHADER_PLATFORM_NAME:STRING="auto" -DKLAYGE_ARCH_NAME:STRING="x64" -DCMAKE_BUILD_TYPE:STRING="Release" ../CMake
CMake Error: The source directory "C:/msys64/home/Administrator/KlayGE/build/CMake" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[W] Config KlayGE failed, retry 1...


C:\msys64\home\Administrator\KlayGE\Build\ninja_mgw122_win_x64-Release>"C:\msys64\mingw64\bin/cmake.EXE" -G "Ninja"  -DKLAYGE_SHADER_PLATFORM_NAME:STRING="auto" -DKLAYGE_ARCH_NAME:STRING="x64" -DCMAKE_BUILD_TYPE:STRING="Release" ../CMake
CMake Error: The source directory "C:/msys64/home/Administrator/KlayGE/build/CMake" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[W] Config KlayGE failed, retry 2...


C:\msys64\home\Administrator\KlayGE\Build\ninja_mgw122_win_x64-Release>"C:\msys64\mingw64\bin/cmake.EXE" -G "Ninja"  -DKLAYGE_SHADER_PLATFORM_NAME:STRING="auto" -DKLAYGE_ARCH_NAME:STRING="x64" -DCMAKE_BUILD_TYPE:STRING="Release" ../CMake
CMake Error: The source directory "C:/msys64/home/Administrator/KlayGE/build/CMake" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[E] Config KlayGE failed.

Press any key to continue . . .

```

**Comment by gongminmin** [comment]
That's what I asked. You want to run inside the msys2. That's not supported. You can just run the Build script in cmd, with mingw64 installed from msys2.

**Comment by gongminmin** [comment]
BTW, mingw-w64-x86_64-gcc and mingw-w64-x86_64-ninja packages are needed.
