### ISSUE TITLE
can't build KlayGE on  my Mac

### ISSUE THREAD

**Issue by NSYXin** [gongminmin/KlayGE#25]
the following build commands failed:
	CompileC /Users/yuanxin/Downloads/KlayGE-develop/KlayGE/Build/clang73_darwin_x64/Engine/Core/KlayGE.build/Debug/KlayGE_Core.build/Objects-normal/x86_64/RenderEffect.o /Users/yuanxin/Downloads/KlayGE-develop/KlayGE/Core/Src/Render/RenderEffect.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[E] Build KlayGE failed.
sh: pause: command not found

**clang version:Apple LLVM version 7.3.0 (clang-703.0.31)**

**Comment by gongminmin** [comment]
Seems mac's sh can't have system("pause") anymore. Could you confirm that @qiankanglai ?

**Comment by qiankanglai** [comment]
Just sent you patch for compiling and fix for `pause`
