### ISSUE TITLE
Following the coding style guide

### ISSUE THREAD

**Issue by gongminmin** [gongminmin/KlayGE#28]
Migrated from trac ticket 30.

Make sure all code are following the coding style guide: http://www.klayge.org/wiki/index.php/C%2B%2B_style_guide

ClangFormat (http://clang.llvm.org/docs/ClangFormat.html) could be useful for this.

**Comment by gongminmin** [comment]
ClangFormat may help.

**Comment by Sangeetha-007** [comment]
I dont understand the issue, but would like to help.

**Comment by gongminmin** [comment]
Thanks very much @Sangeetha-007 . In google's project ANGLE (https://chromium.googlesource.com/angle/angle), they are using ClangFormat to check coding style of every commit. I don't know the detail but it's would be very helpful to have a similar system in KlayGE.
