### ISSUE TITLE
another master build error

### ISSUE THREAD

**Issue by zeyangl** [gongminmin/KlayGE#5]
![image](https://cloud.githubusercontent.com/assets/1244606/7244192/813cb518-e80a-11e4-8164-b6556e7ee3fb.png)

mac 10.10 + xcode 6.2

Is wine supposed to pre-installed?

**Comment by qiankanglai** [comment]
Yes, you need install wine on OSX with homebrew or source code by yourself, because we need wine to run D3DCompile. I think we've uploaded some documents in wiki but I cannot find it now...
Maybe I'll add some prerequisite scripts later, because osx needs wine and linux needs some more.

**Comment by gongminmin** [comment]
Just complete a document on this http://www.klayge.org/wiki/index.php/Installation

**Comment by zeyangl** [comment]
Okay, thx. Will try.
