### ISSUE TITLE
Set "views_dirty_ = false" in D3D11FrameBuffer::OnBind

### ISSUE THREAD

**Issue by liaocheng** [gongminmin/KlayGE#57]
D3D11FrameBuffer，OGLFrameBuffer，D3D12FrameBuffer中
OnBind没有把views_dirty_ 设置为 false，
OnUnbind没有把views_dirty_ 设置为 true。
这导致BindFrameBuffer的时候，即使是同一个FrameBuffer也会触发render target的变化，影响性能

**Comment by gongminmin** [comment]
设置views_dirty_是不对的。views_dirty_表示的是一个framebuffer上的view变化了。OnUnbind并不会改变view的绑定，所以不该设置views_dirty_。而OnBind里如果设置了views_dirty_ = false，在下一次这个framebuffer被bind的时候，就不会调用OMSetRenderTargets来把view设置给D3D11。渲染结果会错。

**Comment by liaocheng** [comment]
在DEFAULT_DEFERRED == TRIDITIONAL_DEFERRED路径中的lighting阶段，对每个灯光调用UpdateLighting时，都会执行re.BindFrameBuffer(pvp.lighting_fb)。而这时pvp.lighting_fb都是同一个对象，但是RenderEngine::BindFrameBuffer中会根据fb->Dirty()(即views_dirty_)来判断是否要真的去执行OnUnbind与OnBind的操作。由于views_dirty_在这时都是true,导致了底层频繁的framebuffer的切换。
如果views_dirty_并不是用于避免这个切换，那是不是要引入另一个属性来避免？

**Comment by liaocheng** [comment]
![image](https://cloud.githubusercontent.com/assets/958492/16354780/6d0b8358-3ad4-11e6-96c3-38c5a15995a3.png)
这是intel pga截取的一个渲染帧。
RT 18是绘制DeferredRenderingAmbient，RT 19是绘制DeferredRenderingSun，这两次绘制的framebuffer应该是同一个，底层确对它进行了重复的bind与unbind操作，导致他们被分割成两个R。T

**Comment by liaocheng** [comment]
![image](https://cloud.githubusercontent.com/assets/958492/16354800/5c67ce3e-3ad5-11e6-8c17-521a309c4878.png)
还有RT 21是绘制skybox,这也应该是在之前的framebuffer上面继续绘制，工具却显示它被单独分成了一个RT

**Comment by gongminmin** [comment]
DEFAULT_DEFERRED == TRIDITIONAL_DEFERRED路径只存在参考意义，而没有实际使用价值。所以没必要去优化它。

即便这里需要修改，减少重复设置，也应该在RenderEngine之类的地方做。这和views_dirty_无关了。

**Comment by gongminmin** [comment]
我正在写一个补丁，把rtv、uav、dsv也cache起来。这样就避免了重复调用OMSetRenderTargets。

**Comment by liaocheng** [comment]
经测试，已经修复
