### ISSUE TITLE
[Question] What's l(xxx) in ASM code

### ISSUE THREAD

**Issue by liaocheng** [gongminmin/KlayGE#68]
在高级语言里面，我们可以直接在shader里面写常量，如
pos += float3(1.0,2.0,3.0);
那么在底层，这个float3(1.0,2.0,3.0)常量是直接保存在shader ASM的字节码里面(像x86或者java的汇编那样放在指令代码区域), 还是和普通的CBuffer一样，先在shader的开始做申明，然后每次切换shader的时候系统自动设置CBuffer?

**Comment by liaocheng** [comment]
![image]https://cloud.githubusercontent.com/assets/2109785/16722210/ae14427c-4777-11e6-83aa-c630c878e9b9.jpg)
用工具反汇编出来是形如 l(1.0 ,2.0, 3.0) 的样子

**Comment by gongminmin** [comment]
SM4+有立即数，敞亮是直接在字节码里面。SM3-就是通过constant register。

**Comment by liaocheng** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/bb943962
是这个东西吗？

**Comment by gongminmin** [comment]
不是。l(0, 1, 2, 3)这个就已经是汇编码了。字节码和它是对应的。
