### ISSUE TITLE
win7 debug模式运行问题

### ISSUE THREAD

**Issue by zgrapher** [gongminmin/KlayGE#7]
klayge 4.6 vs2013 debug运行，会爆在
D3D11RenderEngine.cpp 1212行：
d3d_device_->CheckFormatSupport(fmts[i].second, &s); 

安装dx11 update能解决问题，怀疑跟D3D11_CREATE_DEVICE_DEBUG标志有关。

**Comment by qiankanglai** [comment]
http://www.klayge.org/2013/10/23/%E8%A7%A3%E5%86%B3win7%E4%B8%8A%E7%9A%84d3d11-1%E5%92%8Cwin8-1%E4%B8%8A%E7%9A%84vs2012%E6%97%A0%E6%B3%95%E8%B0%83%E8%AF%95d3d%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by gongminmin** [comment]
Fixed in 6f06c92b8ad40b3bd86b6830be99f7ee6dd21c31.
